# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\pythonScript\PythonWorkspace\easyTest\ui\project\ui_designer\configCenter.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(780, 600)
        Dialog.setSizeGripEnabled(True)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 761, 111))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(160, 10, 60, 20))
        self.label.setObjectName("label")
        self.lineEdit_project = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_project.setGeometry(QtCore.QRect(220, 10, 451, 20))
        self.lineEdit_project.setReadOnly(True)
        self.lineEdit_project.setObjectName("lineEdit_project")
        self.pushButton_open1 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_open1.setGeometry(QtCore.QRect(680, 10, 70, 20))
        self.pushButton_open1.setObjectName("pushButton_open1")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 141, 90))
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(160, 30, 81, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(160, 50, 81, 30))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(160, 80, 81, 20))
        self.label_4.setObjectName("label_4")
        self.label_fangan = QtWidgets.QLabel(self.groupBox)
        self.label_fangan.setGeometry(QtCore.QRect(250, 30, 500, 20))
        self.label_fangan.setObjectName("label_fangan")
        self.label_testCase = QtWidgets.QLabel(self.groupBox)
        self.label_testCase.setGeometry(QtCore.QRect(250, 50, 500, 30))
        self.label_testCase.setObjectName("label_testCase")
        self.label_param = QtWidgets.QLabel(self.groupBox)
        self.label_param.setGeometry(QtCore.QRect(250, 80, 500, 20))
        self.label_param.setObjectName("label_param")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 130, 161, 461))
        self.groupBox_2.setObjectName("groupBox_2")
        self.listWidget_testplan = QtWidgets.QListWidget(self.groupBox_2)
        self.listWidget_testplan.setGeometry(QtCore.QRect(10, 20, 141, 401))
        self.listWidget_testplan.setObjectName("listWidget_testplan")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_testplan.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_testplan.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_testplan.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_testplan.addItem(item)
        self.pushButton_createtestplan = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_createtestplan.setGeometry(QtCore.QRect(10, 430, 60, 23))
        self.pushButton_createtestplan.setObjectName("pushButton_createtestplan")
        self.pushButton_removetestplan = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_removetestplan.setGeometry(QtCore.QRect(90, 430, 60, 23))
        self.pushButton_removetestplan.setObjectName("pushButton_removetestplan")
        self.groupBox_testcase = QtWidgets.QGroupBox(Dialog)
        self.groupBox_testcase.setGeometry(QtCore.QRect(180, 130, 591, 461))
        self.groupBox_testcase.setObjectName("groupBox_testcase")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_testcase)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 20, 491, 101))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.checkBox_ff = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_ff.setGeometry(QtCore.QRect(10, 10, 91, 20))
        self.checkBox_ff.setChecked(True)
        self.checkBox_ff.setObjectName("checkBox_ff")
        self.checkBox_ch = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_ch.setGeometry(QtCore.QRect(10, 40, 71, 20))
        self.checkBox_ch.setObjectName("checkBox_ch")
        self.checkBox_ie = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_ie.setGeometry(QtCore.QRect(10, 70, 50, 20))
        self.checkBox_ie.setObjectName("checkBox_ie")
        self.lineEdit_ffremote = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_ffremote.setEnabled(False)
        self.lineEdit_ffremote.setGeometry(QtCore.QRect(79, 10, 391, 20))
        self.lineEdit_ffremote.setReadOnly(False)
        self.lineEdit_ffremote.setObjectName("lineEdit_ffremote")
        self.lineEdit_chremote = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_chremote.setEnabled(False)
        self.lineEdit_chremote.setGeometry(QtCore.QRect(80, 40, 391, 20))
        self.lineEdit_chremote.setObjectName("lineEdit_chremote")
        self.lineEdit_ieremote = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_ieremote.setEnabled(False)
        self.lineEdit_ieremote.setGeometry(QtCore.QRect(80, 70, 391, 20))
        self.lineEdit_ieremote.setObjectName("lineEdit_ieremote")
        self.tableWidget_testCase = QtWidgets.QTableWidget(self.groupBox_testcase)
        self.tableWidget_testCase.setGeometry(QtCore.QRect(0, 120, 491, 301))
        self.tableWidget_testCase.setObjectName("tableWidget_testCase")
        self.tableWidget_testCase.setColumnCount(5)
        self.tableWidget_testCase.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_testCase.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_testCase.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_testCase.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_testCase.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_testCase.setHorizontalHeaderItem(4, item)
        self.tableWidget_testCase.verticalHeader().setVisible(False)
        self.pushButton_createtestcase = QtWidgets.QPushButton(self.groupBox_testcase)
        self.pushButton_createtestcase.setGeometry(QtCore.QRect(0, 430, 61, 23))
        self.pushButton_createtestcase.setObjectName("pushButton_createtestcase")
        self.pushButton_up = QtWidgets.QPushButton(self.groupBox_testcase)
        self.pushButton_up.setGeometry(QtCore.QRect(70, 430, 61, 23))
        self.pushButton_up.setObjectName("pushButton_up")
        self.pushButton_down = QtWidgets.QPushButton(self.groupBox_testcase)
        self.pushButton_down.setGeometry(QtCore.QRect(140, 430, 61, 23))
        self.pushButton_down.setObjectName("pushButton_down")
        self.pushButton_removetestcase = QtWidgets.QPushButton(self.groupBox_testcase)
        self.pushButton_removetestcase.setGeometry(QtCore.QRect(210, 430, 61, 23))
        self.pushButton_removetestcase.setObjectName("pushButton_removetestcase")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_testcase)
        self.groupBox_5.setGeometry(QtCore.QRect(500, 20, 81, 391))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_save = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_save.setGeometry(QtCore.QRect(10, 10, 60, 30))
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_start = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_start.setGeometry(QtCore.QRect(10, 50, 60, 30))
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_fresh = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_fresh.setGeometry(QtCore.QRect(10, 90, 60, 30))
        self.pushButton_fresh.setObjectName("pushButton_fresh")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "配置中心"))
        self.label.setText(_translate("Dialog", "项目目录："))
        self.pushButton_open1.setText(_translate("Dialog", "打开..."))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; color:#ff007f;\">EasyTest</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-weight:600; color:#aa00ff;\">配置中心</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "测试方案目录："))
        self.label_3.setText(_translate("Dialog", "测试用例目录："))
        self.label_4.setText(_translate("Dialog", "参数化目录："))
        self.label_fangan.setText(_translate("Dialog", "测试方案目录：111111111111111"))
        self.label_testCase.setText(_translate("Dialog", "测试方案目录："))
        self.label_param.setText(_translate("Dialog", "测试方案目录："))
        self.groupBox_2.setTitle(_translate("Dialog", "1.测试方案"))
        __sortingEnabled = self.listWidget_testplan.isSortingEnabled()
        self.listWidget_testplan.setSortingEnabled(False)
        item = self.listWidget_testplan.item(0)
        item.setText(_translate("Dialog", "新建项目"))
        item = self.listWidget_testplan.item(1)
        item.setText(_translate("Dialog", "新建项目"))
        item = self.listWidget_testplan.item(2)
        item.setText(_translate("Dialog", "新建项目"))
        item = self.listWidget_testplan.item(3)
        item.setText(_translate("Dialog", "新建项目"))
        self.listWidget_testplan.setSortingEnabled(__sortingEnabled)
        self.pushButton_createtestplan.setText(_translate("Dialog", "创建方案"))
        self.pushButton_removetestplan.setText(_translate("Dialog", "移除方案"))
        self.groupBox_testcase.setTitle(_translate("Dialog", "2.测试用例套件"))
        self.checkBox_ff.setText(_translate("Dialog", "Firefox"))
        self.checkBox_ch.setText(_translate("Dialog", "Chrome"))
        self.checkBox_ie.setText(_translate("Dialog", "IE"))
        item = self.tableWidget_testCase.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "序号"))
        item = self.tableWidget_testCase.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "启用"))
        item = self.tableWidget_testCase.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "用例名称"))
        item = self.tableWidget_testCase.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "用例路径"))
        item = self.tableWidget_testCase.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "参数化路径"))
        self.pushButton_createtestcase.setText(_translate("Dialog", "添加用例"))
        self.pushButton_up.setText(_translate("Dialog", "上移"))
        self.pushButton_down.setText(_translate("Dialog", "下移"))
        self.pushButton_removetestcase.setText(_translate("Dialog", "移除"))
        self.pushButton_save.setText(_translate("Dialog", "保存"))
        self.pushButton_start.setText(_translate("Dialog", "启动"))
        self.pushButton_fresh.setText(_translate("Dialog", "刷新"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

